//
//  PAFoundation_iOS.h
//  PAFoundation
//
//  Created by ShengQiang on 14-3-5.
//  Copyright (c) 2014年 Ping An Health Insurance Company of China, Ltd. All rights reserved.
//

#import <Foundation/Foundation.h>

enum {
	PABasicLogFileCollectNone  = 0,
	PABasicLogFileCollectNormalLog = 1 << 0,				// Logs generated by PALogger.
	PABasicLogFileCollectCustomCrashLog = 1 << 1,		// Logs generated by CrashLogWriter.
	PABasicLogFileCollectSystemCrashLog = 1 << 2,		// Logs generated by System.
	PABasicLogFileCollectCustomFiles = 1 << 3,			// Other Files specified by setCustomFilesToCollect: 
	PABasicLogFileCollectDirtyFiles = 1 << 4				// Unknown or Unrecorded files in the given log root floder.
};
typedef NSUInteger PABasicLogFileCollectType;


@interface PALogFileCollector : NSObject {
	PABasicLogFileCollectType collectType_;
	PABasicLogFileCollectType clearType_;
	
	NSArray * customFilesToCollect_;
	
	NSString * logRootFloderPath_;
	
	NSString * archivePath_;
	
	BOOL collected_;
}

// You are recommended to call |init| instead of these method.
// Default Log floder and archive path will be specified in |init|.
- (id)initWithLogFloderPath:(NSString *)logFloderPath;
- (id)initWithArchivePath:(NSString *)path;
- (id)initWithLogFloderPath:(NSString *)logFloderPath archivePath:(NSString *)theArchivePath;

- (void)setCollectAndClearType:(PABasicLogFileCollectType)type;
- (void)setCollectType:(PABasicLogFileCollectType)collectType clearType:(PABasicLogFileCollectType)clearType;
- (PABasicLogFileCollectType)collectType;
- (PABasicLogFileCollectType)clearType;

- (void)setCustomFilesToCollect:(NSArray *)filesPathArray;
- (NSArray *)customFilesToCollect;

// the file path of the zip file will be returned.
- (NSString *)startToCollect;
- (NSString *)collectedFilePath;

+ (PABasicLogFileCollectType)PABasicLogFileCollectAll;
+ (PABasicLogFileCollectType)PABasicLogFileCollectAllWithDirtyFiles;
@end
